implemented audio and video files support
prozilla-os/ProzillaOS pull request #24
Opened 2024-10-19 22:45 UTC by Lansa-18

Youtube embeds takes a teeny while to load but it works.

2024-10-20 06:54 UTC, Prozilla requested changes
Looks pretty good, I'll make some final changes myself before merging.

2024-10-20 07:52 UTC, Lansa-18 commented
![Screenshot from 2024-10-20 08-41-32](https://github.com/user-attachments/assets/6fffe744-f93f-4c7b-a42c-c75f1b55ab53)

![Screenshot from 2024-10-20 08-42-49](https://github.com/user-attachments/assets/698b387b-d433-433c-ad40-4039ba6e2814)

![Screenshot from 2024-10-20 08-44-15](https://github.com/user-attachments/assets/fa940b04-277e-4b35-bc1d-a6eec5ea15c9)

2024-10-22 17:19 UTC, Prozilla approved these changes

2024-10-22 17:21 UTC, Prozilla requested changes
Still needs:
- Better interface for audio & video
- Unique file & folder icons for audio & video

2024-10-26 10:34 UTC, merged